import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { AlertTriangle, Shield, Heart } from 'lucide-react';

interface SafetyDisclaimerProps {
  onAccept: () => void;
}

const SafetyDisclaimer: React.FC<SafetyDisclaimerProps> = ({ onAccept }) => {
  const [hasReadDisclaimer, setHasReadDisclaimer] = useState(false);
  const [hasAcknowledgedLimitations, setHasAcknowledgedLimitations] = useState(false);

  const canProceed = hasReadDisclaimer && hasAcknowledgedLimitations;

  return (
    <div className="min-h-screen bg-gradient-therapeutic flex items-center justify-center p-4">
      <Card className="max-w-2xl w-full p-8 shadow-warm bg-card">
        <div className="text-center mb-6">
          <div className="w-16 h-16 bg-gradient-calm rounded-full flex items-center justify-center mx-auto mb-4">
            <Shield className="w-8 h-8 text-primary-foreground" />
          </div>
          <h1 className="text-2xl font-bold text-foreground mb-2">AI Therapy Assistant</h1>
          <p className="text-muted-foreground">Your wellbeing and safety are our top priority</p>
        </div>

        <div className="space-y-6">
          <div className="p-4 bg-warning/10 rounded-lg border border-warning/20">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-warning mt-0.5" />
              <div>
                <h3 className="font-semibold text-warning-foreground mb-2">Important Safety Information</h3>
                <ul className="text-sm text-foreground space-y-1">
                  <li>• This AI assistant is NOT a replacement for professional therapy</li>
                  <li>• In case of emergency, call 911 or your local emergency services</li>
                  <li>• For immediate mental health crisis support, call 988</li>
                  <li>• Always consult qualified healthcare professionals for medical advice</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="space-y-4">
            <h3 className="font-semibold text-foreground flex items-center gap-2">
              <Heart className="w-5 h-5 text-primary" />
              What This AI Can Do
            </h3>
            <ul className="text-sm text-muted-foreground space-y-2 ml-7">
              <li>• Provide supportive listening and empathetic responses</li>
              <li>• Offer basic cognitive behavioral therapy (CBT) techniques</li>
              <li>• Help with emotional regulation and coping strategies</li>
              <li>• Detect signs of distress and provide appropriate resources</li>
              <li>• Guide you to professional help when needed</li>
            </ul>
          </div>

          <div className="space-y-4">
            <h3 className="font-semibold text-foreground">Limitations & Boundaries</h3>
            <ul className="text-sm text-muted-foreground space-y-2">
              <li>• Cannot diagnose mental health conditions</li>
              <li>• Cannot prescribe medications or provide medical treatment</li>
              <li>• Cannot handle emergency situations requiring immediate intervention</li>
              <li>• Responses are generated by AI and may not always be perfect</li>
              <li>• Not suitable for severe mental health crises</li>
            </ul>
          </div>

          <div className="space-y-4 pt-4 border-t">
            <div className="flex items-start space-x-3">
              <Checkbox 
                id="disclaimer" 
                checked={hasReadDisclaimer}
                onCheckedChange={(checked) => setHasReadDisclaimer(checked as boolean)}
              />
              <label htmlFor="disclaimer" className="text-sm text-foreground">
                I have read and understand the safety information and limitations of this AI therapy assistant.
              </label>
            </div>

            <div className="flex items-start space-x-3">
              <Checkbox 
                id="limitations" 
                checked={hasAcknowledgedLimitations}
                onCheckedChange={(checked) => setHasAcknowledgedLimitations(checked as boolean)}
              />
              <label htmlFor="limitations" className="text-sm text-foreground">
                I acknowledge that this AI cannot replace professional therapy and will seek professional help for serious mental health concerns.
              </label>
            </div>
          </div>

          <Button 
            onClick={onAccept}
            disabled={!canProceed}
            className="w-full"
            variant="therapeutic"
            size="lg"
          >
            I Understand - Continue to Chat
          </Button>
        </div>
      </Card>
    </div>
  );
};

export default SafetyDisclaimer;